name: "Run Linter"

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint with Pint
        uses: aglipanci/laravel-pint-action@2.6

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "fix: Files linted with Pint"
